language: python
python:
  - "2.7"
  - "3.4"
  - "3.6"
branches:
  except:
    - piptools-ignore-patch
install:
  - "python -c 'import sys; sys.exit(0 if (3, 3) <= sys.version_info < (3, 4) else 1)' && pip install pip==10.0.1 setuptools==39.2 wheel==0.29.0 || pip install -U setuptools pip wheel"
  - "pip install cram"
  - "pip install ."
script:
  - "cram --shell=/bin/bash tests/*.t"
